### ISSUE TITLE
Replace Numpy arrays by torch tensors

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#100]
At some places for vectors and some operations numpy is used and at other torch, and numpy array might break some excepted behaviour we need to remove use of numpy from SyferText and uses torch and torch tensors instead.

**Comment by sachin-101** [comment]
Yups, numpy isn't supported by PySyft yet. We can move all numpy vectors to torch tensors.

**Comment by AlanAboudib** [comment]
@Nilanshrajput can you include some examples?

**Comment by Nilanshrajput** [comment]
`    default_vector = np.zeros(vectors.shape[1], dtype=vectors.dtype)

    return vectors, default_vector`
this is from syfertext_en_core_web_lg . but earlier it was in vectors.py we use numpy for default vectors and i think the vectors are also numpy array instead of torch.tensor.

**Comment by rajathpatel23** [comment]
Hi All, I would like to contribute to this. I am new to open source, and on Slack channel would like your guidance to get started on this issue.

**Comment by Nilanshrajput** [comment]
Great @rajathpatel23  join SyferText slack channel and you can ask any doubt there, for this issue i will advice you to go through all files and check for import of numpy and it's subsequent usage there and replace it with torch tensor.

**Comment by rajathpatel23** [comment]
Sure, I will go through it and post any questions or updates in the slack channel.

**Comment by rajathpatel23** [comment]
Hi, Can I be assigned the issue ?

**Comment by rajathpatel23** [comment]
Thank you @Nilanshrajput

**Comment by Nilanshrajput** [comment]
Hey @rajathpatel23  are you still working on this, ping me on slack if you have any doubts.

**Comment by rajathpatel23** [comment]
hi @Nilanshrajput  yes I am still working on it. Apologies for the delay, will try to finish it this week

**Comment by Nilanshrajput** [comment]
Hey @rajathpatel23 no problem, i was just checking if you were stuck, thanks for contributing:)

**Comment by ramesht007** [comment]
Hi, can i work on this issue?

**Comment by duggalsu** [comment]
Hi @Nilanshrajput , I would like to work on this if still available

**Comment by Nilanshrajput** [comment]
hey, @duggalsu  this is actually resolved in #132, I forgot to close this issue, thanks for reaching out.
