### ISSUE TITLE
Remove get_encrypted_tokens() method from Doc

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#102]
I think this method should be remove @Nilanshrajput since it allows for token-level frequency attacks that would reveal information  about the corpus.

**Comment by Nilanshrajput** [comment]
Can you explain "token-level frequency attacks"?

**Comment by AlanAboudib** [comment]
Basically, by analyzing the frequency of each token's code, for 1-grams, 2-grams, ..., N-grams, some info could be possibly retrieved in some cases. Though, it would be very difficult to retrieve the exact text. But we are still introducing a vulnerability. Check out this discussion just for an idea of what a frequency attack is

https://crypto.stackexchange.com/questions/18500/how-feasible-is-word-level-frequency-analysis-over-english-or-any-language

**Comment by Nilanshrajput** [comment]
I might be wrong here but I don't think a frequency attack is possible, as I understand you can talk about such attacks when you have some form of encoded data. But that is not possible here as we dont have the access to the vectors but we just have pointers to them. to be able to get frequency of a token you need to compare it's vector with all other, which we cant really do here. 
from just pointers to token vectors frequency attack is not possible

**Comment by sachin-101** [comment]
Yups, @Nilanshrajput we are returned the pointer to the Shared tensor. So, we can't perform a frequency attack using it. 
Also, even if we encrypt the same, document twice using SMPC, we get different encrypted vectors every time. So we can't perform a frequency attack, even on the encrypted vectors (if we happen to get hold of them.)

**Comment by AlanAboudib** [comment]
You are right guys! My bad. I will close this issue
