### ISSUE TITLE
Create a better Readme

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SyferText#103]
[Based on this readme template](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md), we should improve our readmes across all OpenMined projects.

[Please consult the following document for our desired best practices.](https://docs.google.com/document/d/126smq1Gful_mo-x5Wm1M1UJW9CvB8fT9YYZmamNqk0M/edit?usp=sharing)

**Comment by AlanAboudib** [comment]
Thank you @cereallarceny . We will work on this. So does that suggest that extra sections are not recommended ?

**Comment by cereallarceny** [comment]
@em-blue and the writing team will be in touch with you on this issue.

You can totally have extra sections, but I'd highly suggest you think about the content hierarchy.

**Comment by em-blue** [comment]
Extra sections are fine! It's more about making sure all the info on that template is there.

**Comment by AlanAboudib** [comment]
OK great then. We will work on that. Thank you :zap:

**Comment by Nilanshrajput** [comment]
@AlanAboudib I will start on this!

**Comment by AlanAboudib** [comment]
@Nilanshrajput Thank you

**Comment by AlanAboudib** [comment]
@Nilanshrajput any news?
