### ISSUE TITLE
ModuleNotFoundError: No module named 'syfertext_en_core_web_lg'

### ISSUE THREAD

**Issue by kouohhashi** [OpenMined/SyferText#106]
## Question
**Describe your question in ONE SENTENCE.**
When I tried to run the command ```for token in doc:``` at tutorial "Part 0 - (Getting Started) Local Tokenization",  I got an error, ```No module named 'syfertext_en_core_web_lg'```

Is this because syfertext_en_core_web_lg is not installed properly or en_core_web_lg is not installed properly?

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.6
 - Package Manager Version: Conda 4.6.11

**Comment by bicycleman15** [comment]
hey @kouohhashi did you follow the instructions mentioned in the README ?

**Comment by kouohhashi** [comment]
When I run "pip uninstall syfertext_en_core_web_lg" to re-install syfertext_en_core_web_lg, it says "WARNING: Skipping syfertext-en-core-web-lg as it is not installed.".

So it seems syfertext_en_core_web_lg was not installed correctly..

I will try to install syfertext_en_core_web_lg again.

Thank you.

**Comment by kouohhashi** [comment]
It's working after installing syfertext_en_core_web_lg correctly.
Thanks.
