### ISSUE TITLE
Add/complete Documentations 

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#107]
## Where?
Add documentation for `Doc`, `Token`, `vocab` class description as well as for initialisation. 

Add documentation for initialisation.: `Language`

**Comment by AlanAboudib** [comment]
One for code examples, and one in markdown format to go in the /docs folder. 

(The `vocab` and `Language` however need to wait since major changes are coming with PyGrid integration)

**Comment by AlanAboudib** [comment]
I think this issue should be closed. one issue per documentation is way easier to get a handle on.
