### ISSUE TITLE
Endow the Tokenizer with prefix, suffix, infix and exception search rule

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#11]
The current tokenizer is so simplistic. It only performs space-based splitting. 

Processing real datasets requires more sophisticated tokenization.

Thus, prefix, suffix and infix matching rules  and well as the ability to detect exceptions should be added to the tokenizer.

Useful references:

https://spacy.io/usage/linguistic-features#tokenization

https://spacy.io/api/tokenizer

**Comment by dzlab** [comment]
Any reason why do we need to reimplement tokenizers, couldn't we just rely on whatever is available on the worker (spacy, ntlk, etc.)??

**Comment by Nilanshrajput** [comment]
Hi, I want to work on this issue @AlanAboudib . And I think(with only little knowledge of SyferText and PySyft) we need to reimplement the tokenizers as we will be sending our tokenizer to worker for encrypted pre-processing of text and prepare it for encrypted training.

**Comment by AlanAboudib** [comment]
Go ahead @Nilanshrajput. Notice that there is no such thing as encrypted pre-processing. Pre-processing is done directly on plaintext. It is just done blindly meaning that we do not have the right to see the text that is being preprocessed. We only get the encrypted token representation whenever preprocessing is finished

**Comment by AlanAboudib** [comment]
The reason we do not use spacy, nltk, tokenizers directly is because SyferText should not require the installation of another NLP library. It should be as standalone as possible
