### ISSUE TITLE
Send `span_id` via a different method in doc

### ISSUE THREAD

**Issue by bicycleman15** [OpenMined/SyferText#111]
So currently in `__gettiem__` method of `doc`, the check `self.client_id != self.owner.id` sends a `span_id` to the caller, this might break in the case when a pipeline at a remote place uses `doc[i:j]`, becuase in this case, `span_id` will be returned whereas the pipeline was expecting a `Span` class.

My solution is to introduce a new `getitem_id` method in doc, and then we use this method to return `span_id` when accessed by a `DocPointer` and remove the check  `self.client_id != self.owner.id` in doc's `__getitem__`

**Comment by sachin-101** [comment]
Based on our current implementation, the **pipeline is sent** to the machine where the doc resides. So, it will be returned a `Span`. Is this what you are trying to do?

**Comment by bicycleman15** [comment]
Yeah currently a `span_id` is returned, instead a `Span` should be returned to the pipeline.

**Comment by sachin-101** [comment]
Are the pipeline and the doc on the same machine?
If not, then send the pipeline to the remote machine where the doc resides.
If yes, then `Span` should be returned. If `span_id` is returned then there is some issue :fearful: .

**Comment by AlanAboudib** [comment]
@bicycleman15 @sachin-101 in my opinion, it is the responsibility of the remote pipe to know how to handle `span_id`. For instance, if it turns out that there would be cases were a `Matcher` is not allowed to be sent to the remote worker, then we should enable the Matcher to handle this case by operating on span_id through a span pointer

**Comment by bicycleman15** [comment]
I will take this :+1:
