### ISSUE TITLE
SyferText en_core_web_lg vs spaCy en_core_web_lg

### ISSUE THREAD

**Issue by EpcLoler** [OpenMined/SyferText#120]
## Question
How different is the en_core_web_lg between SyferText and spaCy?

## Further Information
This link (https://github.com/OpenMined/SyferText/blob/master/tutorials/Part%200%20-%20(Getting%20Started)%20Local%20Tokenization.ipynb) explicitly tells that SyferText's en_core_web_lg  is a simplified model of spaCy's en_core_web_lg. Some detail regarding this simplification in the readme or in the tutorial would be helpful.
Also, when can the en_core_web_sm version be expected?

**Comment by AlanAboudib** [comment]
Hi @EpcLoler syfertext's model takes only the vector from that of spacy, but it does not include any other components such as 'parsers', NE recognizers or the like.

We are currently working on migrating SyferText to PyGrid, which should be ready soon. Then we will be able to add other language models. You will be welcome to work on this once PyGrid integration is ready in a few weeks

**Comment by EpcLoler** [comment]
Thank for the quick response @AlanAboudib!
