### ISSUE TITLE
Create `SingleLabelClassifier` class

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#136]
An object of this class could be called with `Doc` or `DocPointer` and a `DocEncoder` (described in #137 ) as inputs, and predicts a single class using a PySyft single class classifier. If in MPC mode, this object should securely deliver the predicted class to a `Doc` object using the `set_predicted_classs()` method explained in #134 

We should be able to deploy this class objects as part of a SyferText pipeline by calling `Language.add_pipe()` which implies that this class should also have implementation of the `dump_state()` and `load_state()` methods. Examples of the latter methods implementations can be found in the implementation of the `Tokenizer` class.

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by praveenjoshi01** [comment]
I will be happy to work on this. Are there any dependencies over some other components that are getting built-in parallel?

**Comment by AlanAboudib** [comment]
Hi @praveenjoshi01 , I suggest you start working on this #137 issue which is a dependency of this issue
