### ISSUE TITLE
Implement  a `AverageDocEncoder` class

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#137]
An object of a SyferText classifier class, such a `SinglLabelClassifier` described in #136 is supposed to take a `Doc` or `DocPointer` as inputs when called. The `DocEncoder` object it also takes, takes that `Doc` or `DocPointer` object and produces the input tensor required by the underlying PySyft classifier.

The `DocEncoder` class should be implemented as an abstract class.

A `AverageDocEncoder` is to be implemented as a child of `DocEncoder`. But for simplicity, we can start out for this issue by not implementing the `DocEncoder` class. Such class is to be implemented when more `DocEncoder` classes are needed. 

An object of the `AverageDocEncoder` class simply calls the `Doc` or `DocPointer`'s method `get_encrypted_vector()` if in MPC mode, or simply  `get_vector()` when no encryption is used. It returns the result of the call.

I think that separating the logic of document encoding this way will become handy when integrating HuggingFace transformers, which also uses a similar encoder logic.

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by praveenjoshi01** [comment]
Looks good, can you please assign it to me? Also, yesterday I was facing issues while installation of syfertext. I tried to checkout the dev branch too 0.1.0 to resolve it but still, something looks wrong. It will be great if you can help me a bit to set up and then I will take it forward from there.
