### ISSUE TITLE
Add the `key2row` and `vectors` arguments to `set_vocab`

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#138]
The `Language` class has  a method called `set_vocab()`. This method is used to add a `Vocab` object to a pipeline. However, the implementation of this method is not complete, since it does not enable us to pass the `key2row` and `vectors` arguments that `Vocab` constructor can take.

Please add these argument and test it locally as well as on remote workers.

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by hershd23** [comment]
Hi, is the issue still open? Can I work on this?

**Comment by AlanAboudib** [comment]
@hershd23 I had already started working on this issue. More issues are there in the list, you can check them out, and more are coming soon :)
