### ISSUE TITLE
Error when requesting a vector for out-of-vocabulary tokens

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#14]
In the current version of SyferText, if we tokenize a string containing and out-of-vocabulary token, an exception is raised. Try the following:

```
doc = nlp("hello asdkljflkjsdlfkjlksd")
doc[1].vector
```

This code shoudl raise a `KeyError`.

Instead, it should return a vector of only zeros.

**Comment by dzlab** [comment]
I will work on this one

**Comment by AlanAboudib** [comment]
It's yours @dzlab
