### ISSUE TITLE
Adapt tests to a locally created language model

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#142]
Currently, in SyferText < v0.1.0 , all tests use an experimental language model called `en_core_web_lg` that is adpated from spaCy's language model with the same name.

However, in SyferText v0.1.0, all language models will be hosted on PyGrid. Creating a PyGrid in AWS and hosting models on it might take some time, since we might have some technical issues in PyGrid.

In order to make tests functional, before a PyGrid instance is created on AWS, we can create a local pipeline using `syfertext.create()` already implemented in the `syfertext_0.1.0` branch. This language model should be created only with a `Tokenizer` using `Language.set_tokenizer()` and a `Vocab` using `Language.set_vocab()` with dummy vectors. The code to create it should be included in a separated module in the `tests` folder that we can call `utils.py`. Then we can call `nlp = utils.get_test_language_model()` in `test_*.py` files.

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by ramesht007** [comment]
Hey, @AlanAboudib  I would like to work on this issue

**Comment by AlanAboudib** [comment]
Go ahead @ramesht007 , this issue is dependent on #138 which I am working on, but you can totally start working on it. I will make sure to solve my issue ASAP

**Comment by AlanAboudib** [comment]
Done by @ramesht007 and verified  by @Nilanshrajput in #163
