### ISSUE TITLE
Enforcing type checking in SyferText

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#148]
## What?
Enforcing type checking in SyferText by requiring & enforcing type hints using a decorator.
We can cheat from Great work by @tudorcebere .
https://github.com/OpenMined/PySyft/blob/syft_0.3.0/src/syft/typecheck/typecheck.py

## Additional Context
For syfertext_0.1.0

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by hershd23** [comment]
Seems cool. Can I work on this?

**Comment by Nilanshrajput** [comment]
Sure @hershd23 go ahead!
