### ISSUE TITLE
Adape `SimpleTagger` to remote execution

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#157]
## Feature Description
In order for `SimpleTagger` to operate remotely, we need to implement the `load_state()` and `dump_state()` methods.

Examples on how to implement these methods could be found in `Tokenizer` and `Vocab` classes.

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by ramesht007** [comment]
hey, @AlanAboudib I would like to work on this
Thanks

**Comment by AlanAboudib** [comment]
Go ahead Ramesht

**Comment by AlanAboudib** [comment]
Done by @ramesht007 in #163
