### ISSUE TITLE
Proof Read the SyferText documentation

### ISSUE THREAD

**Issue by hershd23** [OpenMined/SyferText#165]
## Where?
The documentation is currently hosted at :-  https://syfertext.readthedocs.io/en/syfertext_0.1.0/index.html

## What?
Proof read the documentation and point out the errors in docs (grammatical, formatting etc.) and provide any fixes for them if possible

**Comment by darshan-gandhi** [comment]
Hi @hershd23 @Nilanshrajput  could I take up this and work on it? 
Thank you. Look forward to your word.

**Comment by Nilanshrajput** [comment]
Great @darshan-gandhi go ahead!

**Comment by darshan-gandhi** [comment]
Thanks @Nilanshrajput

**Comment by hershd23** [comment]
Ping me on @darshan-gandhi if you have any issues with setting up sphinx locally. For any such error, you can try and play around with the docstring in that file and see if that error gets resolved as we currently read the docstrings in the code to generate documentation. I don't think you'll need to go much into sphinx apart from setting it up and running it locally. Any other suggestions @Nilanshrajput ?

**Comment by darshan-gandhi** [comment]
Thanks @hershd23 ,sounds good. I'll drop you a message on Slack for the same.
