### ISSUE TITLE
Create a vector() method as a property in the  Doc class

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#19]
In the `Doc` class, the method `get_encrypted_vector()` first computes the plain document vector as an average of in-vocabulary tokens' vectors. It then encrypts this vector using SMPC and returns it.

I suggest to take out the part that  the plain average vector and separate it as a standalone method called `vector` that also acts like a property, by annotating it with `@property`. 

This method is then used by `get_encrypted_vector()`

Working on this issue can only start after #17   is merged

**Comment by tsingh2k15** [comment]
@AlanAboudib  can I take this up?

**Comment by AlanAboudib** [comment]
@tsingh2k15 Thank you for interest. There is actually already a PR #21 to fix this issue. 

I will soon add a bunch of issues that you will be able to work on

**Comment by arbazkhan971** [comment]
is this issue still open?
I want to contrbute to good first issues but there isn't anymore left

**Comment by AlanAboudib** [comment]
@arbazkhan971 , this issue was actually solved in #37
