### ISSUE TITLE
Can i get access to syfertext 0.1.0

### ISSUE THREAD

**Issue by Kevin-Lakhani** [OpenMined/SyferText#207]
## Question
**Describe your question in ONE SENTENCE.**

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by AlanAboudib** [comment]
Dear @Kevin-Lakhani, unfortunately, the previous version 0.1.0 was deprecated and support was removed before the version was completely refined. This was due to a complete reboot in PySyft that necessitated new efforts from the team.

What is your need for 0.1.0?
