### ISSUE TITLE
Module not found after succesful installation

### ISSUE THREAD

**Issue by Bhuvan-21** [OpenMined/SyferText#210]
[##]([url](url)) Description
Modules not found after instalation

## How to Reproduce
Code given

## Screenshots
![Screenshot from 2021-04-25 17-07-09](https://user-images.githubusercontent.com/51778760/115992052-3af48b00-a5e9-11eb-9e0f-3d8f080a6a0b.png)

## System Information
 - OS: Ubuntu
 - OS Version: 20

**Comment by AlanAboudib** [comment]
Solved by #211
