### ISSUE TITLE
Convert docstrings into documentation

### ISSUE THREAD

**Issue by MarcioPorto** [OpenMined/SyferText#26]
We've done a great job so far of documenting classes and functions. The next step is to convert this into documentation that can be hosted on something like [Read the Docs](https://readthedocs.org/).

**Comment by AlanAboudib** [comment]
Cannot agree more. Thank you for the issue @MarcioPorto

**Comment by MarcioPorto** [comment]
Np @AlanAboudib! I have actually done this before, so I can work on it 👍

**Comment by bicycleman15** [comment]
Maybe I can help with this @MarcioPorto if you don't mind ?

**Comment by MarcioPorto** [comment]
Sure @bicycleman15! 🚀

**Comment by AlanAboudib** [comment]
@MarcioPorto Can you look back into this issue (PR #39)

**Comment by AlanAboudib** [comment]
Done in #164
