### ISSUE TITLE
Introduce the `StringStore` class and remove the 'text' attribute from the Doc class

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#27]
(Please read the whole conversation to understand the issue )
The document text should not be explicitly stored in `Doc` object. This is a waste of memory. If needed, a document text is to be reconstructed from the individual `Token` objects.

**Comment by datason** [comment]
Alan, please, I want to take this one

**Comment by AlanAboudib** [comment]
Go ahead @datason

**Comment by Nilanshrajput** [comment]
But tokens are note saved anywhere , only token Metadata is stored, and tokens are created on the go from the text using the metadata for each token, I don't understand how it is memory wastage?

**Comment by Nilanshrajput** [comment]
else storing all the tokens would be almost equivalent to storing text, we might probably get away with removing meta data part.

**Comment by AlanAboudib** [comment]
@Nilanshrajput The `text` property I am talking about is that of `Doc` not of `Token`. In `TokenMeta` we only store pointers to the beginning and the end position of the token in the original text.

In the case that the user stores the returned `Doc` objects, this will be an additional waste of memory, since each such object will have a `text` property storing the original text. 

I agree that token meta also takes memory, but I would rather keep one source of memory usage (list of `TokenMeta`) rather than two (`TokenMeta` + `text` property)

**Comment by Shashankjain12** [comment]
So @AlanAboudib what you want is to remove the text argument from doc class and then adding that to the token class and redefining it's method over there?

**Comment by AlanAboudib** [comment]
@Shashankjain12 @datason the plaintext should be stored neither in `Token` not in `TokenMeta` objects.

Actually, a new class called `StringStore` like in spaCy should be created. mappings between plaintext words and hashes should be stored there.

If a new token is encountered by the tokenizer, which has no match in `StringStore` it should be added along with a hash using`utils.hash_string()`.

Then all `TokenMeta` object should have a field called `orth` that stores the hash of the string.

**Comment by AlanAboudib** [comment]
We should be doing all of this because storing string objects spends way more memory than storing 8-byte corresponding hashes that refer to that string in the `StringStore`

**Comment by bicycleman15** [comment]
Can I take this issue ? 
@datason are you still working on this ?

**Comment by datason** [comment]
@bicycleman15 yep, 
I am still working.

**Comment by datason** [comment]
@AlanAboudib 
Do I understand correctly that using `StringStore` will help to store any string only once?
For example, if we have two different `Doc` objects, with same string "hello", we will store "hello" only once.

**Comment by Nilanshrajput** [comment]
@datason 
Possibly There could be a Hashmap like data struct, where key will be hash of strings, and we could only store the key as token data, to restore the original the same hashmap will be called. Some thing in this line.

**Comment by Nilanshrajput** [comment]
@AlanAboudib 
As I understand, in Spacy a shared vocab is initiated after creating nlp(language) object, and all the different docs we create share the same vocab, and that vocab holds the string store. let me know if it's the right direction to go.
