### ISSUE TITLE
Enable worker-side download of  language models

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#3]
The current version of SyferText works with `VirtualWorker`s, which reside on the same machine as the `hook.local_worker`. 

This means that once the language model is downloaded after calling:

```
nlp = syfertext.load('en_core_web_lg', owner = hook.local_worker)
```

The language model is downloaded to the home directory. The `Vocab` and `Vector` objects would be able to access that language model on the home directory. 

However, when using real 'remote' workers, this would give an error, since those objects would try to access the language models on their own machines on which no models were downloaded. An error would occur.

Thus, downloading a language model should be done on each worker before the first tokenization task, not on the `load()` call.

A thought should  be given to how a progress bar for such a remote download should be displayed on the local worker's machine.

**Comment by glitch401** [comment]
Can I work on this ?

**Comment by AlanAboudib** [comment]
Go ahead @glitch401

**Comment by sachin-101** [comment]
@AlanAboudib Downloading language models on remote workers may not be a good idea as they are quite huge and the remote workers might be edge devices with minimal storage. I suggest, that we can instead let the remote worker access the language model on our local machine. Correct me if I am wrong.

**Comment by AlanAboudib** [comment]
Hi @sachin-101 so in case the dataset is private, we need  the language model (especially the word embedding lookup table) to live in the same worker as the dataset. So that the plain text tokens are not revealed in the vector lookup process.

If the remote machine has limited memory, we can download lighter language models, or create language models with vectors that have lower dimensions, or figure out something else ;)

**Comment by sachin-101** [comment]
@AlanAboudib I would like to help with this issue. Any advice on how I should proceed with the implementation ? Will I need to extend pysyft VirtualWorkers to have a load() / download() functionality ?

**Comment by AlanAboudib** [comment]
This issue is no more relevant in the  PyGrid integration context!
