### ISSUE TITLE
Create a unicode tokenizer

### ISSUE THREAD

**Issue by dzlab** [OpenMined/SyferText#34]
Current tokenizer splits on whitespace this can be useful in some cases but usually we want to also split on punctuation and other unicode characters (depending on the language).
We need the following tasks to be done:
* Implement a unicode tokenizer (e.g. on white space and punctuation)
* Add tests with at least two languages of different punctuation (e.g. English and Arabic)

**Comment by AntonioLopardo** [comment]
I can work on this

**Comment by AlanAboudib** [comment]
Hello @dzlab this is a duplicate issue with #11. There is a PR for it that I am reviewing here #25

**Comment by dzlab** [comment]
@AlanAboudib  I see. but just. make sure in the PR we can provide the option to split on whitespaces only vs splitting on whitespaces and punctuation.

**Comment by AlanAboudib** [comment]
@dzlab The tokenizer will be able to separate any punctuation mark into a separate `Token` object. It is non-destructive tokenization. So it will still be whitespace-based. Once this is done, we should add a sentenciser pipe component that can recognize sentences' boudaries based on the Tokenizer's output.
