### ISSUE TITLE
Enable custom-attribute-based token vector exclusion in computing Doc vector

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#43]
When we query the `Doc` vector, we should be able to do something like

```
doc.get_vector(excluded_tokens = {'attribute1_name' : [value1, value2], 
                                  'attribute2_name', [v1, v2], ....})
```

This means that all tokens inside the Doc that has:

```
token._.attribute1_name == value1
token._.attribute1_name == value2
:
:
etc
```

Should not be used when the `Doc`'s average vector is computed

This allows us to use the `SimpleTagger` to tag some tokens (such as stop words, custom words that we think irrelevant) to exclude them from the `Doc` vector

**Comment by AntonioLopardo** [comment]
@AlanAboudib I would like to work on this

**Comment by Nilanshrajput** [comment]
@AlanAboudib I will start working on this.

**Comment by AlanAboudib** [comment]
Go ahead @AntonioLopardo

**Comment by NileshPant1999** [comment]
> Go ahead @AntonioLopardo
Do I need to create a get_vector method in vector function
