### ISSUE TITLE
problem downloading models

### ISSUE THREAD

**Issue by bicycleman15** [OpenMined/SyferText#51]
Consider the scenario I'm downloading the language model and my internet stops, or my the program gets interupted. So the next time I load the model , SyferText thinks its already downloaded but its not and throws an error.
Is there any way around it ? or do we have to manually delete the model files from `SyferText` folder in the `home` directory to fix it.
Keep a md5 for each file maybe ? Just curious.
Of course this will be a problem for large models only.

**Comment by sachin-101** [comment]
Yeah! Had encountered this many times while working on enabling remote download of language models. Deleted the folders manually every time.
