### ISSUE TITLE
StringStore is loading entire Vocab that model knows.

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#59]
We can add string in store dynamically as we come encounter them in data instead of loading the entire vocab at initialization, it will save memory and will be more efficient as well!

**Comment by bicycleman15** [comment]
Can I work on this issue ? : ) @AlanAboudib @Nilanshrajput

**Comment by Nilanshrajput** [comment]
Yup go for it, probably just need to remove just one line for load_strings() call in vocab.py .

**Comment by Nilanshrajput** [comment]
add some test to check  the size of stringStore after creating doc.

**Comment by bicycleman15** [comment]
> Yup go for it @bicycleman15 , probably just need to remove just one line for load_strings() call in vocab.py .

Yeah I saw that. Thanks anyway.
