### ISSUE TITLE
create a span like object for doc

### ISSUE THREAD

**Issue by bicycleman15** [OpenMined/SyferText#62]
I and @sachin-101 were thinking of implementing a span like object that will give us slice of a doc object.
kind of like
```python
span = doc[start:end]
for token in span:
    # do whatever with token
```
We will collaborate on this feature. Just wanted to give a heads up.

**Comment by AlanAboudib** [comment]
Great, that is a good idea that is on the TODO in the project page. Go ahead go!

**Comment by Nilanshrajput** [comment]
@bicycleman15  can you add label attribute in spans, it will useful for ner tagging.
each span object can have a string label, for our usecase it will be name of entity for the span.
