### ISSUE TITLE
Update Vocab class

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#68]
Currently we add/access string in string store by directly accessing string store of vocab, instead __ getitem__() should be defined to any operations before adding a string. 
__ getitem __()will return a Lexeme object for the given text.
Also add extra utility functions like
 __ iter__()  to iterate over currently stored strings,
 __ contains__(), 
get_vector(string_or_orth),
has_vector etc something similar as in spacy(https://spacy.io/api/vocab).
some of these are essential for adding Lexeme object in Vocab.

**Comment by Nilanshrajput** [comment]
@AlanAboudib  I am working on this, let me know if there are some caveats related to this issue.

**Comment by Syzygianinfern0** [comment]
> get_vector(string_or_orth),
> has_vector etc something similar as in spacy(https://spacy.io/api/vocab).
Considering methods like these it would be good to include [different word distances](https://towardsdatascience.com/word-distance-between-word-embeddings-cc3e9cf1d632) between such vectors. Might be good as a follow-up PR.

**Comment by Nilanshrajput** [comment]
@Syzygianinfern0  there is a PR [#50](https://github.com/OpenMined/SyferText/pull/50) for similarity from @bicycleman15 . but for adding different algorithm to calculate that, I think it might be an overkill, we can discuss it later.
