### ISSUE TITLE
Models not downloading

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#70]
https://github.com/AlanAboudib/syfertext_en_core_web_lg/
Model paths in the Repo are changed.

**Comment by sachin-101** [comment]
I guess alan is working on supporting the download of language models as python packages.

**Comment by AlanAboudib** [comment]
Yeah, sorry, I will push a fix for this very shortly. You are right @sachin-101. I am preparing for PyGrid integration.

**Comment by Nilanshrajput** [comment]
Yup i saw that. Just created a issue for anybody wondering why 404 error is coming.

**Comment by AlanAboudib** [comment]
Problem fixed
