### ISSUE TITLE
Wrong owner of Doc object

### ISSUE THREAD

**Issue by sachin-101** [OpenMined/SyferText#73]
`text = String("Building SyferText").send(bob)`
`doc_ptr = nlp(text)`
`doc = bob.get_obj(doc_ptr.id_at_location)`
`print(doc.owner)        # <VirtualWorker id:me #objects:0>`

I think doc.owner should be bob, instead of local worker, since the doc resides on bob's machine.

**Comment by AlanAboudib** [comment]
@sachin-101 can you do another teste where in the __repr__ method, you make the doc object print its owner, then you can see directly its owner by looking at `bob._objects`

I am suspecting that the `get_obj` method itself might be the cause

**Comment by bicycleman15** [comment]
@AlanAboudib This is the same problem I messaged you about a few days ago.
![Screenshot 2020-04-04 at 11 34 23 AM](https://user-images.githubusercontent.com/47978882/79733014-1dc01900-8312-11ea-8e68-9aee9c6d10f1.png)

**Comment by AlanAboudib** [comment]
@justin1121 Thank you, yeah, this is the problem you raised weeks ago. I will check out your PR
