### ISSUE TITLE
tokenize empty string

### ISSUE THREAD

**Issue by bicycleman15** [OpenMined/SyferText#76]
Currently when we try to tokenize an empty string, it throws an error an out of bounds error.
```python
doc = nlp("")
# throws an error
```
@Nilanshrajput can you look into this issue as you worked on the tokenizer recently? Maybe create an empty doc in this case.

**Comment by Nilanshrajput** [comment]
Sure

**Comment by Nilanshrajput** [comment]
returning empty doc []

**Comment by bicycleman15** [comment]
Yes this will work. 👍  Thanks.
