### ISSUE TITLE
Create a document vector as the average of all its token vectors

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#8]
Currently, `DocPointer` and `Doc` classes each have a method called `getEncryptedVector`:

https://github.com/OpenMined/SyferText/blob/98abfc1e94f50e6329333e0acd4994e1e546b117/syfertext/pointers/doc_pointer.py#L31

Those methods should be replaced with `get_vector` that should return an encrypted version of the document vector, which is an average of all of its token vectors

**Comment by dzlab** [comment]
working on this issue
