### ISSUE TITLE
Remove garbage_collect_data argument from all __init__ methods of pointers

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#90]
At the moment, we want garbage collection to be always active when pointers to Doc, SubPipeline object are  lost. 

So each time there is a `garbage_collect_data` in any `__init__` function, this should be removed, in `DocPointer`, `SubPipelinePointer`, and others if exists

**Comment by pranshurastogi29** [comment]
hi i too want to work on this issue so can i joint too

**Comment by sachin-101** [comment]
Go ahead @pranshurastogi29. It's a good first issue and doesn't require in-depth knowledge of SyferText. Still, if you need any help, DM on slack.
