### ISSUE TITLE
Create a tutorial on spans

### ISSUE THREAD

**Issue by bicycleman15** [OpenMined/SyferText#92]
Now that #78 was merged, it would be great if there was some tutorial on its usage.

**Comment by codeboy5** [comment]
Can I work on this ? Want to contribute to syfertext and seems like a good first issue

**Comment by Nilanshrajput** [comment]
great @codeboy5  go ahead.

**Comment by AlanAboudib** [comment]
Hi @codeboy5, any news on this tutorial? Do not hesitate if you need any help

**Comment by codeboy5** [comment]
Hi @AlanAboudib working on it, will open a PR soon

**Comment by codeboy5** [comment]
Hey I have added almost all the features of the span method in the tutorial ? 
There was just one confusion should I present them as practical use cases or just some small example demonstrating the functionality ?
Thanks

**Comment by bicycleman15** [comment]
if you can think of a use case then its great other wise it fine I think @codeboy5

**Comment by neelabh17** [comment]
Are you still working on this @codeboy5 ? Can I take this?

**Comment by Praful932** [comment]
Hello, Seems like a good first issue, Can I work on it?

**Comment by bicycleman15** [comment]
@Praful932 Sure, go ahead. 👍

**Comment by neelabh17** [comment]
Awesome @bicycleman15 

> @Praful932 Sure, go ahead. 👍

**Comment by Praful932** [comment]
> @Praful932 Sure, go ahead. 👍

@bicycleman15 I'll start working on it. I have a few doubts to how the tutorial should exactly be
Should it be similar to the available tutorials like this [one](https://github.com/OpenMined/SyferText/blob/master/tutorials/Part%200%20-%20(Getting%20Started)%20Local%20Tokenization.ipynb)?
Also if I have a doubt, should I ping you here or slack

Thanks

**Comment by bicycleman15** [comment]
@Praful932 can u contact me on slack ? its `@jatin` there.

**Comment by gigatesseract** [comment]
Hi, I'd like to take it up and work on it.Where can I find the URL of slack workspace?
