### ISSUE TITLE
Add Functionality for user-defined exceptions in Tokenizer.

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#97]
Current Tokenizer uses pre-defined exceptions present in 'token_eception.py'. 
here's what current `init` looks like :
`class Tokenizer(AbstractObject):
    def __init__(
        self,
        vocab: Union[Vocab, str],
        exceptions=TOKENIZER_EXCEPTIONS,`

we want to update this initialisation and  add user defined custom exceptions in the the original dictionary containing exceptions(`TOKENIZER_EXCEPTIONS`).

**Comment by shashank-m** [comment]
I can take this up

**Comment by shashank-m** [comment]
Could you give me an example so that I get a clearer picture?

**Comment by Nilanshrajput** [comment]
Great @shashank-m go for it. Here is a small example

`exception = [{'ORTH': "do"}, {'ORTH': "n't"}]
tokenizer.add_exception("don't", exception`
you need to add this method in Tokenizer. this exception will get added in the 'TOKEN_EXCEPTIONS'. look at the token_exception.py file to get clarity regarding creating these exceptions. Message me on slack if you have any further doubts

**Comment by shashank-m** [comment]
Yeah sure

**Comment by AlanAboudib** [comment]
Any PR of this Issue should be merged to branch syfertext_0.1.0

**Comment by someshsingh22** [comment]
Can I work on this if it is still incomplete? @Nilanshrajput

**Comment by Nilanshrajput** [comment]
@AlanAboudib I think this is already Solve in 0.1 should probably close the issue?

**Comment by Nilanshrajput** [comment]
solved in SyferText v0.1.0 branch
