### ISSUE TITLE
Compatibility issue with PySyft future release

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#99]
PySyft latest version on github have updated simplifying and detailing (refer serde.py in Pysyft), which is not compatible with SyferText now.

**Comment by karlhigley** [comment]
Oh no! We're trying to refactor in a direction that makes it possible for SyferText to register its own classes for serialization by PySyft. What did we break?

**Comment by Nilanshrajput** [comment]
` proto_id = max(list(serde.detailers.keys())) + 1` in SyferText init raises NoneType error, detailers is not accessible in this way now. seems like they have removed global variables

**Comment by karlhigley** [comment]
Ah, the global is still there, but it's now initialized at the first use of the serialization via `serde.init_global_vars_msgpack()`. Wonder if this can be fixed by calling that method first before extending?

**Comment by Nilanshrajput** [comment]
yeah i will try this, currently we have pointed syft to pypi latest release.

**Comment by AlanAboudib** [comment]
@karlhigley yeah, whenever you implement registeration in PySyft, we will move to using that. This will avoid such compatibility issues.

**Comment by karlhigley** [comment]
@AlanAboudib We're working on it now. (Really, @tudorcebere is working on it, and I think he has a prototype already.)

**Comment by AlanAboudib** [comment]
@karlhigley great to know, I should watch that PR if one is there already

**Comment by karlhigley** [comment]
Looks like it's posted now: OpenMined/PySyft#3530
